title: Data Activism Program
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Slides: https://destroyer128424.github.io/DataActivismProgram/Slides.html
  Videos: https://destroyer128424.github.io/DataActivismProgram/Videos.html


callouts:
  note:
    title: NOTE
    color: red
