title: Data Activism Program
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  RESOURCES: https://destroyer128424.github.io/DataActivismProgram/Resources.html
